# 一般套件
import re
import os
import time
import asyncio
import argparse
import subprocess
from threading import Lock
from pydantic import BaseModel, Field
from typing_extensions import TypedDict
from typing import Annotated, Literal, List, Dict, Any

# LangChain + LangGraph 套件
from langchain_core.tools import tool
from langchain_openai import ChatOpenAI
from langgraph.types import Command, Send
from langgraph.prebuilt import create_react_agent
from langgraph_supervisor import create_supervisor
from langgraph.checkpoint.memory import MemorySaver
from langchain_mcp_adapters.client import MultiServerMCPClient
from langchain_core.messages import HumanMessage, SystemMessage
from langgraph.graph import StateGraph, START, END, add_messages, MessagesState

# Messages & Job Bus (全域狀態控管)
MESSAGE_BOARD: Dict[str, List[str]] = {}
board_lock = Lock() # for thread-safe access to MESSAGE_BOARD

JOB_LIST: List[Dict[str, Any]] = [] # 外部實例化的 job list
job_lock = Lock() # for thread-safe access to JOB_LIST

# Agent 溝通與狀態工具定義
@tool
def send_message(target_role: str, message: str) -> str:
    """發送訊息給其他協作的 Agent 角色（例如要求 API 規格或回報進度）。"""
    with board_lock:
        if target_role not in MESSAGE_BOARD:
            MESSAGE_BOARD[target_role] = []
        MESSAGE_BOARD[target_role].append(message)
    return f"已成功發送訊息給 {target_role}。"

@tool
def check_messages(my_role: str) -> str:
    """讀取發給自己的訊息。如果有其他 Agent 詢問你問題，請務必處理並回覆。"""
    with board_lock:
        if my_role not in MESSAGE_BOARD or not MESSAGE_BOARD[my_role]:
            return "目前沒有新訊息。"
        msgs = MESSAGE_BOARD[my_role].copy()
        MESSAGE_BOARD[my_role].clear()
        return "\n".join(msgs)

@tool
def wait_for_reply(my_role: str, wait_seconds: int = 5) -> str:
    """當你需要等待其他 Agent 提供資訊時，使用此工具暫停等待，隨後會回傳收到的訊息。"""
    time.sleep(wait_seconds)
    with board_lock:
        if my_role not in MESSAGE_BOARD or not MESSAGE_BOARD[my_role]:
            return "等待超時，目前尚未收到回覆，請決定是否繼續等待或先處理其他事。"
        msgs = MESSAGE_BOARD[my_role].copy()
        MESSAGE_BOARD[my_role].clear()
        return "\n".join(msgs)

@tool
def mark_job_finished(task_description: str) -> str:
    """當你完成一項被指派的具體任務時，呼叫此工具將該任務標記為完成 (finish=True)。"""
    with job_lock:
        for job in JOB_LIST:
            # 簡單字串比對，實務上可改用 ID
            if job['task_description'] == task_description:
                job['finish'] = True
                return f"任務 '{task_description}' 已成功標記為完成。"
        return f"找不到指定的任務 '{task_description}'，請確認任務描述是否完全一致。"

# 定義輸出格式
class TaskJob(BaseModel):
    task_description: str = Field(..., description="The specific job/task description")
    assigned_agent: str = Field(..., description="The role of the agent assigned to this job")

class AgentPlan(BaseModel):
    agent_count: int = Field(..., description="Agent count")
    agent_roles: List[str] = Field(..., description="Roles of the agents")
    agent_prompts: List[str] = Field(..., description="Prompts for the agents")
    jobs: List[TaskJob] = Field(..., description="List of specific jobs generated by the planner to be assigned to agents")
    
class PlanningResult(BaseModel):
    plan: AgentPlan = Field(..., description="The plan for the agents")
    supervisor_prompt: str = Field(..., description="The prompt for the supervisor")

# 定義狀態格式
class DynamicState(TypedDict):
    messages: Annotated[list, add_messages]
    agent_plan: AgentPlan | None
    supervisor_prompt: str | None
    final_result: str | None

# 定義單一Agent的狀態格式 (新增 assigned_jobs)
class AgentTaskState(TypedDict):
    role: str
    prompt: str
    task_description: str
    assigned_jobs: List[str] # 傳遞給 Agent 該負責的具體任務
    all_roles: List[str]

# 檔案操作 Tool定義
@tool
def execute_bash(command: str) -> str:
    """執行 Bash shell 指令並回傳標準輸出 (stdout) 或錯誤訊息 (stderr)。"""
    try:
        result = subprocess.run(
            command, shell=True, check=True, text=True, capture_output=True
        )
        return result.stdout if result.stdout else "指令執行成功，無輸出。"
    except subprocess.CalledProcessError as e:
        return f"指令執行失敗:\nError: {e.stderr}"

@tool
def read_file(file_path: str) -> str:
    """讀取指定檔案的內容。"""
    if not os.path.exists(file_path):
        return f"錯誤: 找不到檔案 {file_path}"
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            return f.read()
    except Exception as e:
        return f"讀取檔案發生錯誤: {str(e)}"

@tool
def write_file(file_path: str, content: str) -> str:
    """新建或覆寫指定檔案的內容。"""
    try:
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
        return f"成功將內容寫入檔案 {file_path}"
    except Exception as e:
        return f"寫入檔案發生錯誤: {str(e)}"

@tool
def append_file(file_path: str, content: str) -> str:
    """在指定檔案的末尾追加內容。"""
    try:
        with open(file_path, 'a', encoding='utf-8') as f:
            f.write(content)
        return f"成功將內容追加到檔案 {file_path}"
    except Exception as e:
        return f"追加檔案發生錯誤: {str(e)}"

# 將 mark_job_finished 加入工具列
agent_tools = [execute_bash, read_file, write_file, append_file, send_message, check_messages, wait_for_reply, mark_job_finished]

# 定義 LLM 模型
NVIDIA_API_KEY = "XXXXX"
NVIDIA_BASE_URL = "https://integrate.api.nvidia.com/v1"
MODEL_NAME = "z-ai/glm5"
model = ChatOpenAI(
    api_key=NVIDIA_API_KEY,
    base_url=NVIDIA_BASE_URL,
    model=MODEL_NAME,
    temperature=0.7
)

# Prompt 定義 (修改提示詞要求生成子任務)
planning_prompt = """你是一個專業的任務拆解與系統規劃專家。請將任務解構為多個子任務(jobs)，並指派給專屬 AI Agent。
請注意：這些 Agent 將會「平行且同時」執行。為確保他們能無縫協作，請針對會產生依賴的職責（例如前端依賴後端API）做好角色劃分與具體的 jobs 規劃，
他們將配備訊息通訊工具來解決依賴問題。
任務描述：{task_description}

請嚴格遵守以下 JSON 格式輸出，不要包含任何其他解釋文字或 Markdown 標記：
{{
  "plan": {{
    "agent_count": 2,
    "agent_roles": ["RoleA", "RoleB"],
    "agent_prompts": ["PromptA", "PromptB"],
    "jobs": [
      {{"task_description": "Job description", "assigned_agent": "RoleA"}}
    ]
  }},
  "supervisor_prompt": "Supervisor prompt here"
}}
"""

def agent_planner(state: DynamicState) -> PlanningResult:
    task_description = state['messages'][-1].content
    prompt = planning_prompt.format(task_description=task_description)
    
    print("\n--- [Planner] 開始規劃任務 ---")
    for _ in range(10):
        try:
            content = ""
            for chunk in model.stream([HumanMessage(content=prompt)]):
                print(chunk.content, end="", flush=True)
                content += chunk.content
            print("\n------------------------------\n")
            
            clean_json_str = re.sub(r'^```(?:json)?\n|\n```$', '', content.strip(), flags=re.MULTILINE)
            parsed_result = PlanningResult.model_validate_json(clean_json_str)
            break
        except:
            prompt = "以下的json輸出格式不正確，請按照json的格式再重新輸出一次。這是之前的輸出內容:\n" + content
    
    return {
        "agent_plan": parsed_result.plan,
        "supervisor_prompt": parsed_result.supervisor_prompt
    }

def dispatch_agents(state: DynamicState) -> List[Send]:
    plan = state["agent_plan"]
    task_description = state["messages"][-1].content
    all_roles = plan.agent_roles

    global MESSAGE_BOARD, JOB_LIST
    MESSAGE_BOARD = {}
    
    # 初始化外部的 Job List
    with job_lock:
        JOB_LIST = [
            {
                "task_description": job.task_description, 
                "assigned_agent": job.assigned_agent, 
                "finish": False
            } 
            for job in plan.jobs
        ]
    
    sends = []
    for role, prompt in zip(plan.agent_roles, plan.agent_prompts):
        # 篩選分配給該 Agent 的 Jobs
        assigned_jobs = [job.task_description for job in plan.jobs if job.assigned_agent == role]
        
        sends.append(Send("Executing", {
            "role": role, 
            "prompt": prompt, 
            "task_description": task_description,
            "assigned_jobs": assigned_jobs,
            "all_roles": all_roles
        }))
    return sends

def agent_executor(state: AgentTaskState) -> dict:
    jobs_str = "\n".join([f"- {job}" for job in state['assigned_jobs']]) if state['assigned_jobs'] else "無特定子任務，請依職責自由發揮。"
    
    system_instruction = f"""你扮演的角色是: {state['role']}
你的整體職責: {state['prompt']}

【你的待辦任務清單 (Jobs)】
{jobs_str}
---
【協作與通訊指示】
目前與你同時運行的同伴有：{', '.join(state['all_roles'])}
1. 若你缺乏某些資訊（例如需要別人決定 API 規格），請主動用 `send_message` 詢問負責的同伴，接著用 `wait_for_reply` 等待。
2. 執行任務期間，請適時呼叫 `check_messages` 檢查是否有人找你。若有，請優先回覆對方所需的資訊。
3. 檔案操作時，務必使用工具實際產生程式碼。
4. 當你完成任何一項「待辦任務清單」上的具體任務時，務必呼叫 `mark_job_finished` 將其標記為完成 (finish=True)。
"""
    agent = create_react_agent(
        model,
        tools=agent_tools,
        prompt=system_instruction
    )
    user_msg = HumanMessage(content=f"總體任務描述: {state['task_description']}")
    response = agent.invoke({"messages": [user_msg]})
    final_message = response["messages"][-1].content
    return {"messages": [f"【{state['role']}】的產出:\n{final_message}"]}

Graph = StateGraph(DynamicState)

Graph.add_node("Planning", agent_planner)
Graph.add_node("Executing", agent_executor)
Graph.add_edge(START, "Planning")
Graph.add_conditional_edges("Planning", dispatch_agents, ["Executing"])
Graph.add_edge("Executing", END)

app = Graph.compile()

# 執行測試
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="AI Agent")
    parser.add_argument(
        "-p", "--prompt", 
        type=str, 
        required=True, 
        help="Please enter the task description for the AI Agent to execute (Prompt)"
    )
    args = parser.parse_args()

    # inputs = {"messages": [HumanMessage(content="幫我在./code/這個路徑，用python的fastapi和html開發一個網頁，是可以讓使用者輸入文字，然後按下送出後，會把使用者輸入的文字顯示在網頁上。")]}
    inputs = {"messages": [HumanMessage(content=args.prompt)]}
    
    for chunk in app.stream(inputs):
        print(chunk)
    
    # 觀察任務清單的最終狀態
    print("\n--- 最終 Job List 狀態 ---")
    for job in JOB_LIST:
        print(f"負責人: {job['assigned_agent']} | 完成: {job['finish']} | 任務: {job['task_description']}")
